---
# Credentials for AAP
controller_credentials:
  - credential_type: Source Control
    name: Git
    description: General token for git
    inputs:
      username: git
      password: password
    organization: Platform
  - credential_type: Vault
    name: ansible-vault
    inputs:
      vault_password: s3cr3t
    description: Ansible Vault Password
    organization: Platform
