---
controller_templates:
  - name: GitOps Reconciliation
    job_type: run
    inventory: Controller
    project: Controller
    playbook: playbook.yml
    credentials:
      - 'ansible-vault'
    state: present
  - name: Deploy Software
    job_type: run
    inventory: Inventory
    project: Project
    playbook: playbook.yml
    credentials:
      - Vagrant
      - 'ansible-vault'
    state: present
